version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env_file:
      - docker.env
    ports:
      - 16543:80
    depends_on: 
      - postgres
    networks: 
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes: 
  pg-data: