//RENAME THIS TO .env
// ADD YOUR OWN ENVIRONMENT VARIABLES HERE
/*

DATABASE_HOST=
DATABASE_USERNAME=
DATABASE_PASSWORD=
DATABASE_NAME=
JWT_SECRET=

*/
// ALSO CREATE A docker.env FILE FOR DOCKER COMPOSE CONFIGURATION VARIABLES
// WITH THE NAMES BELOW

/*
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=
PGADMIN_DEFAULT_EMAIL=
PGADMIN_DEFAULT_PASSWORD=
*/